# Generated by Django 4.2.7 on 2023-11-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kok', models.EmailField(max_length=70, unique=True)),
                ('login', models.CharField(max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('registration_date', models.DateField(default=0)),
            ],
        ),
    ]
