# Generated by Django 4.2.7 on 2023-11-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='kok',
            new_name='email',
        ),
    ]
