# Generated by Django 4.2.7 on 2023-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessbackend', '0002_rename_kok_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
