# Generated by Django 4.2.7 on 2023-11-03 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessbackend', '0003_alter_myuser_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
